package Refinement_Layer.Accumulators;

public class Attributes {
    public static final String[] key_AirQ_Quantity = new String[]{"SOUT_ETOH_SGP30_8373181", "SOUT_H2_SGP30_8373181", "C_CO2eq_SGP30_8373181", "C_TVOC_SGP30_8373181"};
    public static final String[] key_AirQ_Concentration = new String[]{"MassConc_1p0_SPS3x_ECAC46730C998045", "MassConc_2p5_SPS3x_ECAC46730C998045", "MassConc_4p0_SPS3x_ECAC46730C998045", "MassConc_10p_SPS3x_ECAC46730C998045", "NumbConc_0p5_SPS3x_ECAC46730C998045", "NumbConc_1p0_SPS3x_ECAC46730C998045", "NumbConc_2p5_SPS3x_ECAC46730C998045", "NumbConc_2p5_SPS3x_ECAC46730C998045", "NumbConc_10p_SPS3x_ECAC46730C998045", "TypPartSize_SPS3x_ECAC46730C998045"};
    public static final String[] key_Aw = new String[]{"Engine_Load_[%]", "Engine_Speed_[RPM]", "Vehicule_Speed_[km/h]", "fHR", "fRR", "Sensor_1", "Sensor_2", "Sensor_3", "Sensor_4", "Sensor_5", "Sensor_6", "Sensor_7", "Sensor_8"};
    public static final String[] key_Camera = new String[]{"is_face_human", "head_pose_yaw", "head_pose_pitch",	"head_pose_roll", "head_pose_yaw_cal", "head_pose_pitch_cal", "head_pose_roll_cal", "pupil_dilation_ratio", "right_eye_open_perc", "left_eye_open_perc",	"right_eye_open_mm", "left_eye_open_mm", "R_eye_x", "R_eye_y", "R_eye_z", "R_eye_x_cal", "R_eye_y_cal", "R_eye_z_cal", "R_eye_gaze_yaw", "R_eye_gaze_pitch", "R_eye_gaze_yaw_cal", "R_eye_gaze_pitch_cal", "L_eye_x", "L_eye_y", "L_eye_z", "L_eye_x_cal", "L_eye_y_cal", "L_eye_z_cal", "L_eye_gaze_yaw", "L_eye_gaze_pitch", "L_eye_gaze_yaw_cal", "L_eye_gaze_pitch_cal", "gaze_yaw", "gaze_pitch", "gaze_yaw_cal", "gaze_pitch_cal", "gaze_x", "gaze_y", "gaze_z", "gaze_x_cal", "gaze_y_cal", "gaze_z_cal", "head_coord_x", "head_coord_y", "head_coord_z", "head_coord_x_cal", "head_coord_y_cal", "head_coord_z_cal", "id", "user_name", "is_smoking", "is_using_phone", "is_wearing_seatbelt", "has_glasses", "eyes_on_road", "attentiveness", "drowsiness", "aoi", "aoi_x", "aoi_y", "aoi_z"};
    public static final String[] key_BR_RR = new String[]{"BR", "RtoR"};
    public static final String[] key_ECG = new String[]{"ECG"};
    public static final String[] key_General = new String[]{"HR", "BR", "Temp", "Posture", "Activity", "Acceleration", "Battery", "BRAmplitude", "ECGAmplitude", "ECGNoise", "XMin", "XPeak", "YMin", "YPeak", "ZMin", "ZPeak"};
    public static final String[] key_Empatica = new String[]{"Champ 1", "Champ 2", "Champ 3"};
}
